#服务端口号
server:
  port: 7090
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /base-gateway
#日志配置文件以及日志级别
logging:
  config: classpath:logback-spring.xml
  level:
    root: info
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: base-trans #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://trans-serve #匹配后提供服务的路由地址
          predicates:
            - Path=/base-trans/** # 断言，路径相匹配的进行路由
