#服务端口号
server:
  port: 8090
  tomcat:
    uri-encoding: utf-8
#日志配置文件以及日志级别
logging:
  config: classpath:logback-spring.xml
  level:
    root: info
    com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty: warn
    com.alibaba.nacos.client.naming: warn
publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJShk4j9L0Floe+oBOSpoz6/eo3uK6c2ZcaP2ejgNuLvGKqCU0HFrRmo2eIvFjb2P9LAmvuMdCZqNG3ek0uDtk8CAwEAAQ==
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      connection-properties: config.decrypt=true;config.decrypt.key=${publicKey}
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://124.223.89.90:3306/trans?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
      username: root
      password: RzBAlK75SYr5B0nM2W5wd+3ZrQxBylNNt2u5gRBWOGtexoyge4q7aEzFOLMgFGTpR9qpUMViwaH6bkPUwOzA8g==
      # 启用内置过滤器 stat
      filters: stat
      filter:
        config:
          enabled: true
        stat:
          enabled: true
          db-type: mysql
          # 开启慢sql监控，超过2s 就认为是慢sql，记录到日志中
          log-slow-sql: true
          slow-sql-millis: 2000
      # Druid监测
      stat-view-servlet:
        enabled: true # 启用StatViewServlet
        url-pattern: /druid/* # 访问内置监控页面的路径，内置监控页面的首页是/druid/index.html
        reset-enable: false # 不允许清空统计数据,重新计算
        #        allow: 127.0.0.1         # 允许访问的地址，如果allow没有配置或者为空，则允许所有访问
        #        deny: 10.157.147.143    # 拒绝访问的地址，deny优先于allow，如果在deny列表中，就算在allow列表中，也会被拒绝
        login-username: admin # 配置监控页面访问账号
        login-password: admin # 配置监控页面访问密码
      web-stat-filter:
        enabled: true
        url-pattern: /* # 对所有url进行监控
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" # 排除一些不必要的url
        session-stat-enable: true
        session-stat-max-count: 200

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  quartz:
    job-store-type: jdbc #数据库方式
    #是否等待任务执行完毕后，容器才会关闭
    wait-for-jobs-to-complete-on-shutdown: false
    #配置的job是否覆盖已经存在的JOB信息
    overwrite-existing-jobs: true
    jdbc:
      initialize-schema: always #不初始化表结构
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO #默认主机名和时间戳生成实例ID,可以是任何字符串，但对于所有调度程序来说，必须是唯一的 对应qrtz_scheduler_state INSTANCE_NAME字段
            instanceName: clusteredScheduler #quartzScheduler
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore #持久化配置
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate #我们仅为数据库制作了特定于数据库的代理
            useProperties: false #以指示JDBCJobStore将JobDataMaps中的所有值都作为字符串，因此可以作为名称 - 值对存储而不是在BLOB列中以其序列化形式存储更多复杂的对象。从长远来看，这是更安全的，因为您避免了将非String类序列化为BLOB的类版本问题。
            tablePrefix: qrtz_  #数据库表前缀
            misfireThreshold: 60000 #在被认为“失火”之前，调度程序将“容忍”一个Triggers将其下一个启动时间通过的毫秒数。默认值（如果您在配置中未输入此属性）为60000（60秒）。
            clusterCheckinInterval: 15000 #设置此实例“检入”*与群集的其他实例的频率（以毫秒为单位）。影响检测失败实例的速度。
            isClustered: true #打开群集功能
          threadPool: #连接池
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
util:
  properties:
    pwdKey: MEET_BLOG_SECRET_KEY_
    tokenSignKey: m1e2e3t4b5l6o7g8
    tokenExpiration: 7200000
  sm2:
    encryptType: 1 # 0: 加密，1：不加密
    privateKey: 2094F2F0FA446CB390027F06511BD83D8C0FBB535B8D8DFB1258E846C0569A2D
    publicKey: 04C3458C0D22DF1886E7718B252056855BBEB9E2B1B02AB030B45ABD91CD9E63B397A45120172EF272DB94DF285CC8D34E6FB68E6A10102A739B3669040898733B