#服务端口号
server:
  port: 8090
  tomcat:
    uri-encoding: utf-8
#日志配置文件以及日志级别
logging:
  config: classpath:logback-spring.xml
  level:
    root: info
spring:
  application:
    name: trans-serve # 服务名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.24.10:3306/trans?serverTimezone=UTC&characterEncoding=utf-8
      username: root
      password: password
