#服务端口号
server:
  port: 8090
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /base-trans
#日志配置文件以及日志级别
logging:
  config: classpath:logback-spring.xml
  level:
    root: info
spring:
  application:
    name: trans-serve # 服务名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.24.10:3306/trans?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
      username: root
      password: password

      # 启用内置过滤器 stat
      filters: stat
      filter:
        stat:
          enabled: true
          db-type: mysql
          # 开启慢sql监控，超过2s 就认为是慢sql，记录到日志中
          log-slow-sql: true
          slow-sql-millis: 2000
      # Druid监测
      stat-view-servlet:
        enabled: true # 启用StatViewServlet
        url-pattern: /druid/* # 访问内置监控页面的路径，内置监控页面的首页是/druid/index.html
        reset-enable: false # 不允许清空统计数据,重新计算
        #        allow: 127.0.0.1         # 允许访问的地址，如果allow没有配置或者为空，则允许所有访问
        #        deny: 10.157.147.143    # 拒绝访问的地址，deny优先于allow，如果在deny列表中，就算在allow列表中，也会被拒绝
        login-username: admin # 配置监控页面访问账号
        login-password: admin # 配置监控页面访问密码
      web-stat-filter:
        enabled: true
        url-pattern: /* # 对所有url进行监控
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" # 排除一些不必要的url
        session-stat-enable: true
        session-stat-max-count: 200

util:
  properties:
    pwdKey: MEET_BLOG_SECRET_KEY_
    tokenSignKey: m1e2e3t4b5l6o7g8
    tokenExpiration: 7200000